### ISSUE TITLE
app settings - Roles broken, every user is an admin?

### ISSUE THREAD

**Issue by mecjunk** [KennethScott/SpecOps#12]
Does the solution have a functional Windows Auth with roles.   I'm finding that ever user is an admin regardless of how I configure the application.config file.   Removing the admin role breaks the application as well.

Inquiring as to whether roles was ever implemented or if this would need to be fixed.

**Comment by mecjunk** [comment]
If the admin role is left blank or user assignment is not in the domain\\user|group format then it appears all users will receive the admin role.  So not exactly a defect but appears to be more of a personal error in the a--settings.conf file

**Comment by KennethScott** [comment]
Thank you for reporting this! I have been wanting to overhaul this app for
awhile, but just haven't had time due to other priorities/life right now.
I'll definitely put this on the list to address though.  Thanks again-
