### ISSUE TITLE
No authenticationScheme was specified when trying to run using machine name and local user

### ISSUE THREAD

**Issue by MostHated** [KennethScott/SpecOps#4]
Hey there,
Using the binary release, I get a page that never loads and then trying to run from source I tried to put in my machine name and user on my desktop, it is giving:

```cs
An unhandled exception occurred while processing the request.
InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found. The default schemes can be set using either AddAuthentication(string defaultScheme) or AddAuthentication(Action<AuthenticationOptions> configureOptions).
Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, string scheme, AuthenticationProperties properties)
```

![](https://i.imgur.com/2sYkbY1.png)

Thanks,
-MH

**Comment by KennethScott** [comment]
That makes me think the app is trying to run without Windows Authentication enabled - possibly in both scenarios, but let's start with running it from source via Visual Studio.  I'm assuming you're running with IIS Express?  Can you check the launch profile and make sure Windows Authentication is enabled (and anonymous is disabled)?  It should look something like this:


![image](https://user-images.githubusercontent.com/823499/147617956-2e7cc1dd-cbc5-45ed-98a3-b8519bbcd137.png)


Similarly, when you're setting up the site in IIS to run from the precompiled zip, you'd also want to make sure Windows Authentication is enabled, and Anonymous is disabled:


![image](https://user-images.githubusercontent.com/823499/147618055-18292fe4-234a-44ce-bd35-2ca622724362.png)

Can you try that and let me know if makes any difference?

**Comment by MostHated** [comment]
Oh, I didn't realize IIS Express was required to run it. I must have missed that. I had simply tried to run it as is, I assumed that since it was loading up an running a port that it was not required. I can install it and get it set up if need be?

**Comment by MostHated** [comment]
That seems to have been the issue. I was selecting "SpecOps" then run, but I see there was "IIS Express" as one of the dropdowns to run, I selected that and now it ran properly. My apologies, most of my C# experience has been directly related to Unity, I am not super familiar with ASP or related things, so that's my bad.

**Comment by KennethScott** [comment]
Ah ok, great!  Glad you got it running!

**Comment by MostHated** [comment]
One last quick question, if you happen to know and don't mind. Is this type of application a candidate for being built as a standalone PWA? I realize that is probably a tall order in terms of actually doing so, but could be quite useful in terms of zipping it up and sending to someone bundled with XYZ scripts.

**Comment by KennethScott** [comment]
That's an interesting idea, but I'm afraid I'm not familiar enough with PWAs to really answer.  The thinking with this application being hosted/web-based is really more about installing it one time in an intranet/enterprise-type environment and then allowing users from various areas to access it easily without any installation of any kind on their part.  They'd just be visiting another intranet website.  They can even link directly so specific scripts (from documentation or a knowledgebase, for example).  I'm sure a PWA could also do this, I guess I'm just not familiar enough with the pros/cons compared to a web app in this scenario.
