### ISSUE TITLE
Possibility for logoff

### ISSUE THREAD

**Issue by Domanaik** [KennethScott/SpecOps#7]
Currently I'm just testing SpecOps.

A possibility to logoff would be very nice as some parts I want to do as my adminaccount and some I want to execute use my personal account. (different categories)

Would it be possible to use the current logged-in user to execute the script instead of the iis apppool\specops who is currently executing the powershell scripts?

**Comment by KennethScott** [comment]
Delegating security (or even allowing the security principal to be set via configuration/per script) is something a couple of others have also asked about.  I'd love to be able to add it if I can find some time to work on it.  I just took a new job and time is a little tight right now.  I definitely have it on my to-do list though, although I honestly don't know how feasible it is as I haven't had a chance to really dig into it yet.  I'm always happy to accept PR's if you're so inclined!  :)

**Comment by KennethScott** [comment]
Hey sorry it's taken so long, but I've just posted a new release that has a new script parameter available - EnableImpersonation.  When set to true, it will use the current user's security context to run the script.  Check it out and let me know what you think.  Thanks!
