### ISSUE TITLE
Using the Menu ID in the script

### ISSUE THREAD

**Issue by jeff-estes-saggs** [KennethScott/SpecOps#9]
Is there any way to get the ScriptID as a param in the script.  An example if you have one would be great.  Trying to use one script but with a switch statement based on the scriptID or even name.  Each menu item would be its own function module.

**Comment by KennethScott** [comment]
There's two different ways you could pretty easily add the scriptId to the list of parameters available within the powershell script:
1)  Server-side in the [StreamPowerShell method](https://github.com/KennethScott/SpecOps/blob/master/SpecOps/Hubs/PowershellHub.cs#L60).  If you'll notice I'm already explicitly adding 2 parameters for SpecOpsCurrentUser and SpecOpsCurrentUserIP.  You'd just add another for the scriptId which is already available as a parameter being passed into that method.
```csharp
scriptParameters.Add("SpecOpsScriptId", scriptId);
```
2)  Client-side in [Scripts.cshtml](https://github.com/KennethScott/SpecOps/blob/master/SpecOps/Pages/User/Scripts.cshtml#L294) in the on click handler for the runScript button.  You'd just need to add the scriptId to the parameters collection being created there like:
```javascript
parameters["SpecOpsScriptId"] = $('#ScriptId').val();
```
I've got a growing little to-do list of things for the app I've been trying to find some time to work on.  I'll make a note to add it server-side like I did the CurrentUser and CurrentUserIP when I get a chance.  Worst case you should be able to just edit the cshtml file and get it going for now though.  Hope it helps-

**Comment by KennethScott** [comment]
Hey sorry it's taken so long, but I've just posted a new release that has the SpecOpsScriptId parameter we discussed.  Thanks!
